const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
  TOGGLE_CART_VISIBILITY: 'TOGGLE_CART_VISIBILITY'
};

export default CartActionTypes;
